version: '2'
volumes:
  dbdata:
    external:
      name: 'homemade-dbdata'
  uploads:
    external:
      name: 'homemade-uploads'
  assets:
    external:
      name: 'homemade-assets'

services:
  db:
    image: 'dtheus/postgres'
    env_file: .rbenv-vars
    volumes:
      - 'dbdata:/var/lib/pgsql'

  smtp:
    image: 'dtheus/postfix-dkim'
    ports:
      - '25:25'
    env_file: .rbenv-vars
    volumes: 
      - '/etc/opendkim/keys/homemade-msk.ru:/etc/opendkim/keys/homemade-msk.ru'

  app1: &app
    build: .
    links:
      - db
      - smtp
    env_file: .rbenv-vars
    command: [bundle, exec, thin, start, --config=config/thin.yml]
    volumes:
      - '/home/web/app/public'
      - 'assets:/home/web/app/public/assets'
      - 'uploads:/home/web/app/public/uploads'

  app2:
    <<: *app
    command: [bundle, exec, thin, start, --config=config/thin.yml, --ssl]

  app3:
    <<: *app
    command: [bundle, exec, thin, start, --config=config/thin.yml, --ssl]

  proxy:
    image: 'dtheus/nginx'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './config/nginx.conf:/etc/nginx/nginx.conf'
      - './config/certs:/etc/ssl/certs'
    volumes_from:
      - app1:ro
    links:
      - app1
      - app2
      - app3

