# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f38b3bc13d4dabd2e1f14166aae3587435e50b9c16327c5e54d8b1b0ae7537a1d18d01bcf6a596f47d8a3fc50ceb3b3190bafba10c651d3ec21442ee7ad1941

test:
  secret_key_base: fc3219ee054eabfb040d67548a4fe067aab32b5582e7069c9a7fef3b0213fb95fd6d445a9b0c5a24f865633e23e5b158d298c454049987f8c7e16424b361d183

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
